---
- name: Configure Vault and Boundary Server
  hosts: server
  become: yes
  vars:
    # This password is for bootstrapping only. Vault will rotate it immediately.
    postgres_bootstrap_password: "ThisIsAReallyBadPassword123!"
  roles:
    - role: vault
    - role: postgres
    - role: vault_db_config
    - role: ping_test